//
//  Jokes.swift
//  Shared
//
//  Created by Alex Littlejohn on 10/07/2020.
//  Copyright © 2020 zero. All rights reserved.
//

public let jokes = [
  Joke(setup: "What did the fish say when it hit the wall?", punchline: "Dam."),
  Joke(setup: "How do you make a tissue dance?", punchline: "You put a little boogie on it."),
  Joke(setup: "What's Forrest Gump's password?", punchline: "1Forrest1"),
  Joke(setup: "What do you call a belt made out of watches?", punchline: "A waist of time."),
  Joke(setup: "Why can't bicycles stand on their own?", punchline: "They are two tired"),
  Joke(setup: "How does a train eat?", punchline: "It goes chew, chew"),
  Joke(setup: "What do you call a singing Laptop", punchline: "A Dell"),
  Joke(setup: "How many lips does a flower have?", punchline: "Tulips"),
  Joke(setup: "How do you organize an outer space party?", punchline: "You planet"),
  Joke(setup: "What kind of shoes does a thief wear?", punchline: "Sneakers"),
  Joke(setup: "What's the best time to go to the dentist?", punchline: "Tooth hurty."),
  Joke(setup: "Did you hear about the two silk worms in a race?", punchline: "It ended in a tie."),
  Joke(setup: "What do you call a laughing motorcycle?", punchline: "A Yamahahahaha."),
  Joke(setup: "A termite walks into a bar and says...", punchline: "'Where is the bar tended?'"),
  Joke(setup: "What does C.S. Lewis keep at the back of his wardrobe?", punchline: "Narnia business!"),
  Joke(setup: "What did the duck say when he bought lipstick?", punchline: "Put it on my bill"),
  Joke(setup: "What happens to a frog's car when it breaks down?", punchline: "It gets toad away"),
  Joke(setup: "did you know the first French fries weren't cooked in France?", punchline: "they were cooked in Greece"),
  Joke(setup: "Why did the mushroom get invited to the party?", punchline: "Because he was a fungi."),
  Joke(setup: "I'm reading a book about anti-gravity...", punchline: "It's impossible to put down"),
  Joke(setup: "If you're American when you go into the bathroom, and American when you come out, what are you when you're in there?", punchline: "European"),
  Joke(setup: "Want to hear a joke about a piece of paper?", punchline: "Never mind...it's tearable"),
  Joke(setup: "I just watched a documentary about beavers.", punchline: "It was the best dam show I ever saw"),
  Joke(setup: "If you see a robbery at an Apple Store...", punchline: "Does that make you an iWitness?"),
  Joke(setup: "A ham sandwhich walks into a bar and orders a beer. The bartender says...", punchline: "I'm sorry, we don't serve food here"),
  Joke(setup: "Why did the Clydesdale give the pony a glass of water?", punchline: "Because he was a little horse"),
  Joke(setup: "If you boil a clown...", punchline: "Do you get a laughing stock?"),
  Joke(setup: "Finally realized why my plant sits around doing nothing all day...", punchline: "He loves his pot."),
  Joke(setup: "Don't look at the eclipse through a colander.", punchline: "You'll strain your eyes."),
  Joke(setup: "I bought some shoes from a drug dealer.", punchline: "I don't know what he laced them with, but I was tripping all day!"),
  Joke(setup: "Why do chicken coops only have two doors?", punchline: "Because if they had four, they would be chicken sedans"),
  Joke(setup: "What do you call a factory that sells passable products?", punchline: "A satisfactory"),
  Joke(setup: "When a dad drives past a graveyard: Did you know that's a popular cemetery?", punchline: "Yep, people are just dying to get in there"),
  Joke(setup: "Why did the invisible man turn down the job offer?", punchline: "He couldn't see himself doing it"),
  Joke(setup: "How do you make holy water?", punchline: "You boil the hell out of it"),
  Joke(setup: "I had a dream that I was a muffler last night.", punchline: "I woke up exhausted!"),
  Joke(setup: "Why is peter pan always flying?", punchline: "Because he neverlands"),
  Joke(setup: "What do you call a cow with no legs?", punchline: "Ground beef!"),
  Joke(setup: "I dropped a pear in my car this morning.", punchline: "You should drop another one, then you would have a pair."),
  Joke(setup: "Lady: How do I spread love in this cruel world?", punchline: "Random Dude: [...💘]"),
  Joke(setup: "What do you call sad coffee?", punchline: "Despresso."),
  Joke(setup: "Why did the butcher work extra hours at the shop?", punchline: "To make ends meat."),
  Joke(setup: "Did you hear about the hungry clock?", punchline: "It went back four seconds."),
  Joke(setup: "Well...", punchline: "That’s a deep subject."),
  Joke(setup: "Did you hear the story about the cheese that saved the world?", punchline: "It was legend dairy."),
  Joke(setup: "Did you watch the new comic book movie?", punchline: "It was very graphic!"),
  Joke(setup: "I started a new business making yachts in my attic this year...", punchline: "The sails are going through the roof."),
  Joke(setup: "I got hit in the head by a soda can, but it didn't hurt that much...", punchline: "It was a soft drink."),
  Joke(setup: "I can't tell if i like this blender...", punchline: "It keeps giving me mixed results."),
  Joke(setup: "I couldn't get a reservation at the library...", punchline: "They were fully booked."),
  Joke(setup: "What do you give to a lemon in need?", punchline: "Lemonaid."),
  Joke(setup: "Never take advice from electrons.", punchline: "They are always negative."),
  Joke(setup: "Hey, dad, did you get a haircut?", punchline: "No, I got them all cut."),
  Joke(setup: "What time is it?", punchline: "I don't know... it keeps changing."),
  Joke(setup: "A weasel walks into a bar. The bartender says, \"Wow, I've never served a weasel before. What can I get for you?\"", punchline: "Pop,goes the weasel."),
  Joke(setup: "Bad at golf?", punchline: "Join the club."),
  Joke(setup: "Can a kangaroo jump higher than the Empire State Building?", punchline: "Of course. The Empire State Building can't jump."),
  Joke(setup: "Can February march?", punchline: "No, but April may."),
  Joke(setup: "Can I watch the TV?", punchline: "Yes, but don’t turn it on."),
  Joke(setup: "Dad, can you put my shoes on?", punchline: "I don't think they'll fit me."),
  Joke(setup: "Did you hear about the bread factory burning down?", punchline: "They say the business is toast."),
  Joke(setup: "Did you hear about the chameleon who couldn't change color?", punchline: "They had a reptile dysfunction."),
  Joke(setup: "Did you hear about the cheese factory that exploded in France?", punchline: "There was nothing left but de Brie."),
  Joke(setup: "Did you hear about the cow who jumped over the barbed wire fence?", punchline: "It was udder destruction."),
  Joke(setup: "Did you hear about the guy who invented Lifesavers?", punchline: "They say he made a mint."),
  Joke(setup: "Did you hear about the guy whose whole left side was cut off?", punchline: "He's all right now."),
  Joke(setup: "Did you hear about the kidnapping at school?", punchline: "It's ok, he woke up."),
  Joke(setup: "Did you hear about the Mexican train killer?", punchline: "He had loco motives"),
  Joke(setup: "Did you hear about the new restaurant on the moon?", punchline: "The food is great, but there’s just no atmosphere."),
  Joke(setup: "Did you hear about the runner who was criticized?", punchline: "He just took it in stride"),
  Joke(setup: "Did you hear about the scientist who was lab partners with a pot of boiling water?", punchline: "He had a very esteemed colleague."),
  Joke(setup: "Did you hear about the submarine industry?", punchline: "It really took a dive..."),
  Joke(setup: "Did you hear that David lost his ID in prague?", punchline: "Now we just have to call him Dav."),
  Joke(setup: "Did you hear that the police have a warrant out on a midget psychic ripping people off?", punchline: "It reads \"Small medium at large.\""),
  Joke(setup: "Did you hear the joke about the wandering nun?", punchline: "She was a roman catholic."),
  Joke(setup: "Did you hear the news?", punchline: "FedEx and UPS are merging. They’re going to go by the name Fed-Up from now on."),
  Joke(setup: "Did you hear the one about the guy with the broken hearing aid?", punchline: "Neither did he."),
  Joke(setup: "Did you know crocodiles could grow up to 15 feet?", punchline: "But most just have 4."),
  Joke(setup: "What do ghosts call their true love?", punchline: "Their ghoul-friend"),
  Joke(setup: "Did you know that protons have mass?", punchline: "I didn't even know they were catholic."),
  Joke(setup: "Did you know you should always take an extra pair of pants golfing?", punchline: "Just in case you get a hole in one."),
  Joke(setup: "Do I enjoy making courthouse puns?", punchline: "Guilty"),
  Joke(setup: "Do you know where you can get chicken broth in bulk?", punchline: "The stock market."),
  Joke(setup: "Do you want a brief explanation of what an acorn is?", punchline: "In a nutshell, it's an oak tree."),
  Joke(setup: "Ever wondered why bees hum?", punchline: "It's because they don't know the words."),
  Joke(setup: "Have you ever heard of a music group called Cellophane?", punchline: "They mostly wrap."),
  Joke(setup: "Have you heard of the band 1023MB?", punchline: "They haven't got a gig yet."),
  Joke(setup: "Have you heard the rumor going around about butter?", punchline: "Never mind, I shouldn't spread it."),
  Joke(setup: "How are false teeth like stars?", punchline: "They come out at night!"),
  Joke(setup: "How can you tell a vampire has a cold?", punchline: "They start coffin."),
  Joke(setup: "How come a man driving a train got struck by lightning?", punchline: "He was a good conductor."),
  Joke(setup: "How come the stadium got hot after the game?", punchline: "Because all of the fans left."),
  Joke(setup: "How did Darth Vader know what Luke was getting for Christmas?", punchline: "He felt his presents."),
  Joke(setup: "How did the hipster burn the roof of his mouth?", punchline: "He ate the pizza before it was cool."),
  Joke(setup: "How do hens stay fit?", punchline: "They always egg-cercise!"),
  Joke(setup: "How do locomotives know where they're going?", punchline: "Lots of training"),
  Joke(setup: "How do the trees get on the internet?", punchline: "They log on."),
  Joke(setup: "How do you find Will Smith in the snow?", punchline: " Look for fresh prints."),
  Joke(setup: "How do you fix a broken pizza?", punchline: "With tomato paste."),
  Joke(setup: "How do you fix a damaged jack-o-lantern?", punchline: "You use a pumpkin patch."),
  Joke(setup: "How do you get a baby alien to sleep?", punchline: " You rocket."),
  Joke(setup: "How do you get two whales in a car?", punchline: "Start in England and drive West."),
  Joke(setup: "How do you know if there’s an elephant under your bed?", punchline: "Your head hits the ceiling!"),
  Joke(setup: "How do you make a hankie dance?", punchline: "Put a little boogie in it."),
  Joke(setup: "How do you make holy water?", punchline: "You boil the hell out of it."),
  Joke(setup: "How do you organize a space party?", punchline: "You planet."),
  Joke(setup: "How do you steal a coat?", punchline: "You jacket."),
  Joke(setup: "How do you tell the difference between a crocodile and an alligator?", punchline: "You will see one later and one in a while."),
  Joke(setup: "How does a dyslexic poet write?", punchline: "Inverse."),
  Joke(setup: "How does a French skeleton say hello?", punchline: "Bone-jour."),
  Joke(setup: "How does a penguin build it’s house?", punchline: "Igloos it together."),
  Joke(setup: "How does a scientist freshen their breath?", punchline: "With experi-mints!"),
  Joke(setup: "How does the moon cut his hair?", punchline: "Eclipse it."),
  Joke(setup: "How many apples grow on a tree?", punchline: "All of them!"),
  Joke(setup: "How many bones are in the human hand?", punchline: "A handful of them."),
  Joke(setup: "How many hipsters does it take to change a lightbulb?", punchline: "Oh, it's a really obscure number. You've probably never heard of it."),
  Joke(setup: "How many kids with ADD does it take to change a lightbulb?", punchline: "Let's go ride bikes!"),
  Joke(setup: "How many optometrists does it take to change a light bulb?", punchline: "1 or 2? 1... or 2?"),
  Joke(setup: "How many seconds are in a year?", punchline: "12. January 2nd, February 2nd, March 2nd, April 2nd.... etc"),
  Joke(setup: "How many South Americans does it take to change a lightbulb?", punchline: "A Brazilian"),
  Joke(setup: "How many tickles does it take to tickle an octopus?", punchline: "Ten-tickles!"),
  Joke(setup: "How much does a hipster weigh?", punchline: "An instagram."),
  Joke(setup: "How was the snow globe feeling after the storm?", punchline: "A little shaken."),
  Joke(setup: "Is the pool safe for diving?", punchline: "It deep ends."),
  Joke(setup: "Is there a hole in your shoe?", punchline: "No… Then how’d you get your foot in it?"),
  Joke(setup: "What did the spaghetti say to the other spaghetti?", punchline: "Pasta la vista, baby!"),
  Joke(setup: "What’s 50 Cent’s name in Zimbabwe?", punchline: "200 Dollars."),
  Joke(setup: "Want to hear a chimney joke?", punchline: "Got stacks of em! First one's on the house"),
  Joke(setup: "Want to hear a joke about construction?", punchline: "Nah, I'm still working on it."),
  Joke(setup: "Want to hear my pizza joke?", punchline: "Never mind, it's too cheesy."),
  Joke(setup: "What animal is always at a game of cricket?", punchline: "A bat."),
  Joke(setup: "What are the strongest days of the week?", punchline: "Saturday and Sunday...the rest are weekdays."),
  Joke(setup: "What cookies do hobbits like?", punchline: "Shortbread."),
  Joke(setup: "What cheese can never be yours?", punchline: "Nacho cheese."),
  Joke(setup: "What creature is smarter than a talking parrot?", punchline: "A spelling bee."),
  Joke(setup: "What did celery say when he broke up with his girlfriend?", punchline: "She wasn't right for me, so I really don't carrot all."),
  Joke(setup: "What did Michael Jackson name his denim store?", punchline: "   Billy Jeans!"),
  Joke(setup: "What did one nut say as he chased another nut?", punchline: " I'm a cashew!"),
  Joke(setup: "What did one plate say to the other plate?", punchline: "Dinner is on me!"),
  Joke(setup: "What did one snowman say to the other snow man?", punchline: "Do you smell carrot?"),
  Joke(setup: "What did one wall say to the other wall?", punchline: "I'll meet you at the corner!"),
  Joke(setup: "What did Romans use to cut pizza before the rolling cutter was invented?", punchline: "Lil Caesars"),
  Joke(setup: "What did the 0 say to the 8?", punchline: "Nice belt."),
  Joke(setup: "What did the beaver say to the tree?", punchline: "It's been nice gnawing you."),
  Joke(setup: "What did the big flower say to the littler flower?", punchline: "Hi, bud!"),
  Joke(setup: "What did the Buffalo say to his little boy when he dropped him off at school?", punchline: "Bison."),
  Joke(setup: "What did the digital clock say to the grandfather clock?", punchline: "Look, no hands!"),
  Joke(setup: "What did the dog say to the two trees?", punchline: "Bark bark."),
  Joke(setup: "What did the Dorito farmer say to the other Dorito farmer?", punchline: "Cool Ranch!"),
  Joke(setup: "What did the fish say when it swam into a wall?", punchline: "Damn!"),
  Joke(setup: "What did the grape do when he got stepped on?", punchline: "He let out a little wine."),
  Joke(setup: "What did the judge say to the dentist?", punchline: "Do you swear to pull the tooth, the whole tooth and nothing but the tooth?"),
  Joke(setup: "What did the late tomato say to the early tomato?", punchline: "I’ll ketch up"),
  Joke(setup: "What did the left eye say to the right eye?", punchline: "Between us, something smells!"),
  Joke(setup: "What did the mountain climber name his son?", punchline: "Cliff."),
  Joke(setup: "What did the ocean say to the beach?", punchline: "Thanks for all the sediment."),
  Joke(setup: "What did the ocean say to the shore?", punchline: "Nothing, it just waved."),
  Joke(setup: "Why don't you find hippopotamuses hiding in trees?", punchline: "They're really good at it."),
  Joke(setup: "What did the pirate say on his 80th birthday?", punchline: "Aye Matey!"),
  Joke(setup: "What did the Red light say to the Green light?", punchline: "Don't look at me I'm changing!"),
  Joke(setup: "What did the scarf say to the hat?", punchline: "You go on ahead, I am going to hang around a bit longer."),
  Joke(setup: "What did the shy pebble wish for?", punchline: "That she was a little boulder."),
  Joke(setup: "What did the traffic light say to the car as it passed?", punchline: "Don't look I'm changing!"),
  Joke(setup: "What did the Zen Buddist say to the hotdog vendor?", punchline: "Make me one with everything."),
  Joke(setup: "What do birds give out on Halloween?", punchline: "Tweets."),
  Joke(setup: "What do I look like?", punchline: "A JOKE MACHINE!?"),
  Joke(setup: "What do prisoners use to call each other?", punchline: "Cell phones."),
  Joke(setup: "What do vegetarian zombies eat?", punchline: "Grrrrrainnnnnssss."),
  Joke(setup: "What do you call a bear with no teeth?", punchline: "A gummy bear!"),
  Joke(setup: "What do you call a bee that lives in America?", punchline: "A USB."),
  Joke(setup: "What do you call a boomerang that won't come back?", punchline: "A stick."),
  Joke(setup: "What do you call a careful wolf?", punchline: "Aware wolf."),
  Joke(setup: "What do you call a cow on a trampoline?", punchline: "A milk shake!"),
  Joke(setup: "What do you call a cow with no legs?", punchline: "Ground beef."),
  Joke(setup: "What do you call a cow with two legs?", punchline: "Lean beef."),
  Joke(setup: "What do you call a crowd of chess players bragging about their wins in a hotel lobby?", punchline: "Chess nuts boasting in an open foyer."),
  Joke(setup: "What do you call a dad that has fallen through the ice?", punchline: "A Popsicle."),
  Joke(setup: "What do you call a dictionary on drugs?", punchline: "High definition."),
  Joke(setup: "what do you call a dog that can do magic tricks?", punchline: "a labracadabrador"),
  Joke(setup: "What do you call a droid that takes the long way around?", punchline: "R2 detour."),
  Joke(setup: "What do you call a duck that gets all A's?", punchline: "A wise quacker."),
  Joke(setup: "What do you call a fake noodle?", punchline: "An impasta."),
  Joke(setup: "What do you call a fashionable lawn statue with an excellent sense of rhythmn?", punchline: "A metro-gnome"),
  Joke(setup: "What do you call a fat psychic?", punchline: "A four-chin teller."),
  Joke(setup: "What do you call a fly without wings?", punchline: "A walk."),
  Joke(setup: "What do you call a girl between two posts?", punchline: "Annette."),
  Joke(setup: "What do you call a group of disorganized cats?", punchline: "A cat-tastrophe."),
  Joke(setup: "What do you call a group of killer whales playing instruments?", punchline: "An Orca-stra."),
  Joke(setup: "What do you call a monkey in a mine field?", punchline: "A babooooom!"),
  Joke(setup: "What do you call a nervous javelin thrower?", punchline: "Shakespeare."),
  Joke(setup: "What do you call a pig that knows karate?", punchline: "A pork chop!"),
  Joke(setup: "What do you call a pig with three eyes?", punchline: "Piiig"),
  Joke(setup: "What do you call a pile of cats?", punchline: " A Meowtain."),
  Joke(setup: "What do you call a sheep with no legs?", punchline: "A cloud."),
  Joke(setup: "What do you call a troublesome Canadian high schooler?", punchline: "A poutine."),
  Joke(setup: "What do you call an alligator in a vest?", punchline: "An in-vest-igator!"),
  Joke(setup: "What do you call an Argentinian with a rubber toe?", punchline: "Roberto"),
  Joke(setup: "What do you call an eagle who can play the piano?", punchline: "Talonted!"),
  Joke(setup: "What do you call an elephant that doesn’t matter?", punchline: "An irrelephant."),
  Joke(setup: "What do you call an old snowman?", punchline: "Water."),
  Joke(setup: "What do you call cheese by itself?", punchline: "Provolone."),
  Joke(setup: "What do you call corn that joins the army?", punchline: "Kernel."),
  Joke(setup: "What do you call someone with no nose?", punchline: "Nobody knows."),
  Joke(setup: "What do you call two barracuda fish?", punchline: " A Pairacuda!"),
  Joke(setup: "What do you do on a remote island?", punchline: "Try and find the TV island it belongs to."),
  Joke(setup: "What do you do when you see a space man?", punchline: "Park your car, man."),
  Joke(setup: "What do you get hanging from Apple trees?", punchline: "Sore arms."),
  Joke(setup: "What do you get when you cross a bee and a sheep?", punchline: "A bah-humbug."),
  Joke(setup: "What do you get when you cross a chicken with a skunk?", punchline: "A fowl smell!"),
  Joke(setup: "What do you get when you cross a rabbit with a water hose?", punchline: "Hare spray."),
  Joke(setup: "What do you get when you cross a snowman with a vampire?", punchline: "Frostbite."),
  Joke(setup: "What do you give a sick lemon?", punchline: "Lemonaid."),
  Joke(setup: "What does a clock do when it's hungry?", punchline: "It goes back four seconds!"),
  Joke(setup: "What does a female snake use for support?", punchline: "A co-Bra!"),
  Joke(setup: "What does a pirate pay for his corn?", punchline: "A buccaneer!"),
  Joke(setup: "What does an angry pepper do?", punchline: "It gets jalapeño face."),
  Joke(setup: "What happens to a frog's car when it breaks down?", punchline: "It gets toad."),
  Joke(setup: "What happens when you anger a brain surgeon?", punchline: "They will give you a piece of your mind."),
  Joke(setup: "What has ears but cannot hear?", punchline: "A field of corn."),
  Joke(setup: "What is a centipedes's favorite Beatle song?", punchline: " I want to hold your hand, hand, hand, hand..."),
  Joke(setup: "What is a tornado's favorite game to play?", punchline: "Twister!"),
  Joke(setup: "What is a vampire's favorite fruit?", punchline: "A blood orange."),
  Joke(setup: "What is a witch's favorite subject in school?", punchline: "Spelling!"),
  Joke(setup: "What is red and smells like blue paint?", punchline: "Red paint!"),
  Joke(setup: "What is the difference between ignorance and apathy?", punchline: "I don't know and I don't care."),
  Joke(setup: "What is the hardest part about sky diving?", punchline: "The ground."),
  Joke(setup: "What is the leading cause of dry skin?", punchline: "Towels"),
  Joke(setup: "What is the least spoken language in the world?", punchline: "Sign Language"),
  Joke(setup: "What is the tallest building in the world?", punchline: "The library, it’s got the most stories!"),
  Joke(setup: "What is this movie about?", punchline: "It is about 2 hours long."),
  Joke(setup: "What kind of award did the dentist receive?", punchline: "A little plaque."),
  Joke(setup: "What kind of bagel can fly?", punchline: "A plain bagel."),
  Joke(setup: "What kind of dinosaur loves to sleep?", punchline: "A stega-snore-us."),
  Joke(setup: "What kind of dog lives in a particle accelerator?", punchline: "A Fermilabrador Retriever."),
  Joke(setup: "What kind of magic do cows believe in?", punchline: "MOODOO."),
  Joke(setup: "What kind of music do planets listen to?", punchline: "Nep-tunes."),
  Joke(setup: "What kind of pants do ghosts wear?", punchline: "Boo jeans."),
  Joke(setup: "What kind of tree fits in your hand?", punchline: "A palm tree!"),
  Joke(setup: "What lies at the bottom of the ocean and twitches?", punchline: "A nervous wreck."),
  Joke(setup: "What musical instrument is found in the bathroom?", punchline: "A tuba toothpaste."),
  Joke(setup: "What time did the man go to the dentist?", punchline: "Tooth hurt-y."),
  Joke(setup: "What type of music do balloons hate?", punchline: "Pop music!"),
  Joke(setup: "What was a more important invention than the first telephone?", punchline: "The second one."),
  Joke(setup: "What was the pumpkin’s favorite sport?", punchline: "Squash."),
  Joke(setup: "What's black and white and read all over?", punchline: "The newspaper."),
  Joke(setup: "What's blue and not very heavy?", punchline: " Light blue."),
  Joke(setup: "What's brown and sticky?", punchline: "A stick."),
  Joke(setup: "What's orange and sounds like a parrot?", punchline: "A Carrot."),
  Joke(setup: "What's red and bad for your teeth?", punchline: "A Brick."),
  Joke(setup: "What's the best thing about elevator jokes?", punchline: "They work on so many levels."),
  Joke(setup: "What's the difference between a guitar and a fish?", punchline: "You can tune a guitar but you can't \"tuna\"fish!"),
  Joke(setup: "What's the difference between a hippo and a zippo?", punchline: "One is really heavy, the other is a little lighter."),
  Joke(setup: "What's the difference between a seal and a sea lion?", punchline: "An ion! "),
  Joke(setup: "What's the worst part about being a cross-eyed teacher?", punchline: "They can't control their pupils."),
  Joke(setup: "What's the worst thing about ancient history class?", punchline: "The teachers tend to Babylon."),
  Joke(setup: "What’s brown and sounds like a bell?", punchline: "Dung!"),
  Joke(setup: "What’s E.T. short for?", punchline: "He’s only got little legs."),
  Joke(setup: "What’s Forest Gump’s Facebook password?", punchline: "1forest1"),
  Joke(setup: "What’s the advantage of living in Switzerland?", punchline: "Well, the flag is a big plus."),
  Joke(setup: "What’s the difference between an African elephant and an Indian elephant?", punchline: "About 5000 miles."),
  Joke(setup: "When do doctors get angry?", punchline: "When they run out of patients."),
  Joke(setup: "When does a joke become a dad joke?", punchline: "When it becomes apparent."),
  Joke(setup: "When is a door not a door?", punchline: "When it's ajar."),
  Joke(setup: "Where did you learn to make ice cream?", punchline: "Sunday school."),
  Joke(setup: "Where do bees go to the bathroom?", punchline: " The BP station."),
  Joke(setup: "Where do hamburgers go to dance?", punchline: "The meat-ball."),
  Joke(setup: "Where do rabbits go after they get married?", punchline: "On a bunny-moon."),
  Joke(setup: "Where do sheep go to get their hair cut?", punchline: "The baa-baa shop."),
  Joke(setup: "Where do you learn to make banana splits?", punchline: "At sundae school."),
  Joke(setup: "Where do young cows eat lunch?", punchline: "In the calf-ateria."),
  Joke(setup: "Where does batman go to the bathroom?", punchline: "The batroom."),
  Joke(setup: "Where does Fonzie like to go for lunch?", punchline: "Chick-Fil-Eyyyyyyyy."),
  Joke(setup: "Where does Napoleon keep his armies?", punchline: "In his sleevies."),
  Joke(setup: "Where was the Declaration of Independence signed?", punchline: "At the bottom! "),
  Joke(setup: "Where’s the bin?", punchline: "I haven’t been anywhere!"),
  Joke(setup: "Which side of the chicken has more feathers?", punchline: "The outside."),
  Joke(setup: "Who did the wizard marry?", punchline: "His ghoul-friend"),
  Joke(setup: "Who is the coolest Doctor in the hospital?", punchline: "The hip Doctor!"),
  Joke(setup: "Why are fish easy to weigh?", punchline: "Because they have their own scales."),
  Joke(setup: "Why are fish so smart?", punchline: "Because they live in schools!"),
  Joke(setup: "Why are ghosts bad liars?", punchline: "Because you can see right through them!"),
  Joke(setup: "Why are graveyards so noisy?", punchline: "Because of all the coffin."),
  Joke(setup: "Why are mummys scared of vacation?", punchline: "They're afraid to unwind."),
  Joke(setup: "Why are oranges the smartest fruit?", punchline: "Because they are made to concentrate. "),
  Joke(setup: "Why are pirates called pirates?", punchline: "Because they arrr!"),
  Joke(setup: "Why are skeletons so calm?", punchline: "Because nothing gets under their skin."),
  Joke(setup: "Why can't a bicycle stand on its own?", punchline: "It's two-tired."),
  Joke(setup: "Why can't you use \"Beef stew\"as a password?", punchline: "Because it's not stroganoff."),
  Joke(setup: "Why can't your nose be 12 inches long?", punchline: "Because then it'd be a foot!"),
  Joke(setup: "Why can’t you hear a pterodactyl go to the bathroom?", punchline: "The p is silent."),
  Joke(setup: "Why couldn't the kid see the pirate movie?", punchline: "Because it was rated arrr!"),
  Joke(setup: "Why couldn't the lifeguard save the hippie?", punchline: "He was too far out, man."),
  Joke(setup: "Why did Dracula lie in the wrong coffin?", punchline: "He made a grave mistake."),
  Joke(setup: "Why did Sweden start painting barcodes on the sides of their battleships?", punchline: "So they could Scandinavian."),
  Joke(setup: "Why did the A go to the bathroom and come out as an E?", punchline: "Because he had a vowel movement."),
  Joke(setup: "Why did the barber win the race?", punchline: "He took a short cut."),
  Joke(setup: "Why did the belt go to prison?", punchline: "He held up a pair of pants!"),
  Joke(setup: "Why did the burglar hang his mugshot on the wall?", punchline: "To prove that he was framed!"),
  Joke(setup: "Why did the chicken get a penalty?", punchline: "For fowl play."),
  Joke(setup: "Why did the Clydesdale give the pony a glass of water?", punchline: "Because he was a little horse!"),
  Joke(setup: "Why did the coffee file a police report?", punchline: "It got mugged."),
  Joke(setup: "Why did the cookie cry?", punchline: "Because his mother was a wafer so long"),
  Joke(setup: "Why did the cookie cry?", punchline: "It was feeling crumby."),
  Joke(setup: "Why did the cowboy have a weiner dog?", punchline: "Somebody told him to get a long little doggy."),
  Joke(setup: "Why did the fireman wear red, white, and blue suspenders?", punchline: "To hold his pants up."),
  Joke(setup: "Why did the girl smear peanut butter on the road?", punchline: "To go with the traffic jam."),
  Joke(setup: "Why did the half blind man fall in the well?", punchline: "Because he couldn't see that well!"),
  Joke(setup: "Why did the house go to the doctor?", punchline: "It was having window panes."),
  Joke(setup: "Why did the kid cross the playground?", punchline: "To get to the other slide."),
  Joke(setup: "Why did the man put his money in the freezer?", punchline: "He wanted cold hard cash!"),
  Joke(setup: "Why did the man run around his bed?", punchline: "Because he was trying to catch up on his sleep!"),
  Joke(setup: "Why did the melons plan a big wedding?", punchline: "Because they cantaloupe!"),
  Joke(setup: "Why did the octopus beat the shark in a fight?", punchline: "Because it was well armed."),
  Joke(setup: "Why did the opera singer go sailing?", punchline: "They wanted to hit the high Cs."),
  Joke(setup: "Why did the scarecrow win an award?", punchline: "Because he was outstanding in his field."),
  Joke(setup: "Why did the tomato blush?", punchline: "Because it saw the salad dressing."),
  Joke(setup: "Why did the tree go to the dentist?", punchline: "It needed a root canal."),
  Joke(setup: "Why did the worker get fired from the orange juice factory?", punchline: "Lack of concentration."),
  Joke(setup: "Why didn't the number 4 get into the nightclub?", punchline: "Because he is 2 square."),
  Joke(setup: "Why didn’t the orange win the race?", punchline: "It ran out of juice."),
  Joke(setup: "Why didn’t the skeleton cross the road?", punchline: "Because he had no guts."),
  Joke(setup: "Why do bananas have to put on sunscreen before they go to the beach?", punchline: "Because they might peel!"),
  Joke(setup: "Why do bears have hairy coats?", punchline: "Fur protection."),
  Joke(setup: "Why do bees have sticky hair?", punchline: "Because they use honey combs!"),
  Joke(setup: "Why do bees hum?", punchline: "Because they don't know the words."),
  Joke(setup: "Why do birds fly south for the winter?", punchline: "Because it's too far to walk."),
  Joke(setup: "Why do choirs keep buckets handy?", punchline: "So they can carry their tune"),
  Joke(setup: "Why do crabs never give to charity?", punchline: "Because they’re shellfish."),
  Joke(setup: "Why do ducks make great detectives?", punchline: "They always quack the case."),
  Joke(setup: "Why do mathematicians hate the U.S.?", punchline: "Because it's indivisible."),
  Joke(setup: "Why do pirates not know the alphabet?", punchline: "They always get stuck at \"C\"."),
  Joke(setup: "Why do pumpkins sit on people’s porches?", punchline: "They have no hands to knock on the door."),
  Joke(setup: "Why do scuba divers fall backwards into the water?", punchline: "Because if they fell forwards they’d still be in the boat."),
  Joke(setup: "Why do trees seem suspicious on sunny days?", punchline: "Dunno, they're just a bit shady."),
  Joke(setup: "Why do valley girls hang out in odd numbered groups?", punchline: "Because they can't even."),
  Joke(setup: "Why do wizards clean their teeth three times a day?", punchline: "To prevent bat breath!"),
  Joke(setup: "Why do you never see elephants hiding in trees?", punchline: "Because they're so good at it."),
  Joke(setup: "Why does a chicken coop only have two doors?", punchline: "Because if it had four doors it would be a chicken sedan."),
  Joke(setup: "Why does a Moon-rock taste better than an Earth-rock?", punchline: "Because it's a little meteor."),
  Joke(setup: "Why does it take longer to get from 1st to 2nd base, than it does to get from 2nd to 3rd base?", punchline: "Because there’s a Shortstop in between!"),
  Joke(setup: "Why does Norway have barcodes on their battleships?", punchline: "So when they get back to port, they can Scandinavian."),
  Joke(setup: "Why does Superman get invited to dinners?", punchline: "Because he is a Supperhero."),
  Joke(setup: "Why does Waldo only wear stripes?", punchline: "Because he doesn't want to be spotted."),
  Joke(setup: "Two guys walk into a bar . . .", punchline: "The first guy says \"Ouch!\" and the second says \"Yeah, I didn't see it either.\""),
  Joke(setup: "I saw a nice stereo on Craigslist for $1. Seller says the volume is stuck on ‘high’", punchline: "I couldn’t turn it down."),
  Joke(setup: "My older brother always tore the last pages of my comic books, and never told me why.", punchline: "I had to draw my own conclusions.")
]

